hw02 - Конфигурирование Spring-приложений
dirtystarvan/2024-01-otus-spring-shishkin pull request #3
Opened 2024-02-15 21:20 UTC by dirtystarvan

2024-02-20 00:24 UTC, VladimirMagerov requested changes

2024-02-20 00:24 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +    private static final String TEST_FILE_NAME = "questions.csv";
Как я понимаю, вы используете один и тот же файл с вопросами и для основной программы, и для тестов - это не правильно, так как в случае изменение данных в самой программе, вам придётся ещё переписывать и тесты. Тестовые данные должны быть отдельным файлом.

2024-02-20 00:24 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        assertFalse(questions.isEmpty());
То, что был получен не пустой список, ещё не означает, что он правильный. Предлагаю переписать тест таким образом, чтобы проверялись все данные полностью - количество вопросов, их формулировка, количество вариантов ответа, сами ответы и т.д.

2024-02-20 00:24 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        var testResult = testService.executeTestFor(student);
В данном тесте не было задано никакое поведение для моков зависимостей ( IOService и QuestionDao, соответственно, в самом тесте они ведут себя непредсказуемо. Предлагаю сначала задать поведение для зависимостей тестируемого сервиса (через Mockito.when(), например - можно использовать этот гайд https://www.tutorialspoint.com/mockito/mockito_junit_integration.htm), а только затем вызвать сам тестируемый метод.

2024-02-20 00:24 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        assertEquals(student, testResult.getStudent());
Этой проверки тоже мало - нужны более точные, со сравнением конкретных значений.

2024-02-21 21:11 UTC, dirtystarvan commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        assertFalse(questions.isEmpty());
Добавил

2024-02-21 21:12 UTC, dirtystarvan commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        var testResult = testService.executeTestFor(student);
Добавил

2024-02-21 21:12 UTC, dirtystarvan commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        assertEquals(student, testResult.getStudent());
Добавил

2024-02-22 16:53 UTC, VladimirMagerov approved these changes

2024-02-23 11:06 UTC, merged