hw03 - spring boot
dirtystarvan/2024-01-otus-spring-shishkin pull request #4
Opened 2024-02-24 18:22 UTC by dirtystarvan

2024-02-27 21:26 UTC, VladimirMagerov requested changes

2024-02-27 21:26 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/Application.java
> +		testRunner.run();
Для выполнения кода при запуске приложения в SpringBoot будет удобнее и правильнее использовать специальные интерфейсы - ApplicationRunner или CommandLineRunner, немного поподробнее можно посмотреть тут: https://stackoverflow.com/questions/59328583/when-and-why-do-we-need-applicationrunner-and-runner-interface

Предлагаю использовать один из них и избавится от зависимостей внутри этого класса и PostConstruct-a - они будут просто не нужны (и помним про принцип Single Responsibility).

2024-02-28 20:44 UTC, dirtystarvan commented on hw03/src/main/java/ru/otus/hw/Application.java
> +		testRunner.run();
Да, спасибо, как раз думал как тут лучше выйти из положения.

2024-03-01 09:55 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/service/TestRunnerServiceImpl.java
> +public class TestRunnerServiceImpl implements TestRunnerService, CommandLineRunner {
Кажется, тут произошло некоторое смешение понятий. У нас есть `TestRunnerService`, который запускает тест, и  `CommandLineRunner `, который запускает код при запуске приложения. Если мы объединяем это всё в один класс, то мы сильно нарушаем single responsibility принцип. Что будет, если нам надо будет в будущем запускать другой код при запуске приложения? Или, меняя код в реализации `TestRunnerServiceImpl` каким-то образом повлияем и на выполнение кода при запуске? В общем, возникает много потенциальных проблем.
Предлагаю логику выполнения кода при запуске приложения вынести в отдельный класс и не смешивать её с логикой запуска теста. Если мы так поступим, отдельный класс с реализацией `CommandLineRunner ` сможет просто вызывать код из `TestRunnerService`, но никак не сможет на него повлиять.

2024-03-05 15:09 UTC, VladimirMagerov approved these changes

2024-03-05 18:19 UTC, merged